##########
# SITE SETTINGS
##########

title: PSYOPTICS Collection
tagline: A digital exhibit of COINTELPRO documents
description: "A curated collection of declassified FBI documents related to COINTELPRO operations."

author: Ananya and Syd

##########
# COLLECTION SETTINGS
##########

# Use the filename WITHOUT the .csv extension
metadata: metadata

##########
# BUILD SETTINGS
##########

exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]

sass:
  style: compressed
